// Bundles web/hormony-app.html into src/web/hormonyHtml.ts so Metro ships the UI inside the app.
// Runs automatically before `npm start` / `npm run ios|android|web`; run `npm run build:web` after editing the HTML.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'web', 'hormony-app.html'), 'utf8');
if (html.split('<script>').length !== 2) {
  throw new Error('web/hormony-app.html must contain exactly one <script> tag (the shell injects its config before it).');
}
mkdirSync(join(root, 'src', 'web'), { recursive: true });
writeFileSync(
  join(root, 'src', 'web', 'hormonyHtml.ts'),
  '// GENERATED by scripts/build-web.mjs from web/hormony-app.html. Do not edit; edit the HTML and run `npm run build:web`.\n' +
    `export const HORMONY_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`src/web/hormonyHtml.ts written (${Math.round(html.length / 1024)} KB)`);
